name: CI

on: [push]

jobs:
  my_first_job:
    runs-on: [ubuntu-latest]
    steps:
      # use GitHub Actions
        - uses: actions/checkout@v2
        - name: ls
          run: ls
        - name: cd
          run: cd tools/build/libwebrtc
        - name: ls
          run: ls
        - name: Config
          run: |
          cd tools/build/libwebrtc && \
          sudo ./config.sh -d /mnt/d/build_webrtc -b branch-heads/71 -t android -c arm64
        - name: CheckOut
          run: sudo ./checkout.sh 
        - name: Build
          run: sudo ./build.sh -c Release
        
