name: CI

on: [push]

jobs:
  my_first_job:
    runs-on: [ubuntu-latest]
    steps:
      # use GitHub Actions
        - uses: actions/checkout@v2
        - name: ls
          run: ls
          shell: bash
        - name: Config
          run:  sudo ./tools/build/libwebrtc/config.sh -d /mnt/d/build_webrtc -b branch-heads/71 -t android -c arm64
          shell: bash
        - name: CheckOut
          run: sudo ./tools/build/libwebrtc/checkout.sh 
          shell: bash
        - name: Build
          run: sudo ./tools/build/libwebrtc/build.sh -c Release
          shell: bash
        
